manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: rzssh
      url-base: https://github.com/rzssh
    - name: anywhy
      url-base: https://github.com/anywhy-io

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 268b1b1e82150460f00fd701bcd08583d5c75d29
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: bc114546392b4615ac90a99140eaf21dde31209d
    - name: zmk-adaptive-key
      remote: rzssh
      revision: 540b774f6da9d763e61bc64b694790757ed3bd84
    - name: flake-zmk-module
      remote: anywhy
      revision: dc2f905b491be7b79d3c3ea348eacd80f8c46f98

  self:
    path: config
