USER_NAME := razen

BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = yes
MAGIC_ENABLE = no
NKRO_ENABLE = no
OLED_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
SPACE_CADET_ENABLE = no

ifeq ($(strip $(RAZEN_CYGNUS_QMK)),yes)
    SERIAL_DRIVER = vendor
    OPT_DEFS += -DRAZEN_CYGNUS_QMK
endif
