USER_NAME := razen

BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
GRAVE_ESC_ENABLE = no
I2C_DRIVER_REQUIRED = yes
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = yes
MAGIC_ENABLE = no
NKRO_ENABLE = no
OLED_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
SRC += trackpad.c
# Aurora Sweep models per-key LEDs and underglow LEDs in RGB Matrix.
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
SPACE_CADET_ENABLE = no
