USER_NAME := razen

BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = yes
MAGIC_ENABLE = no
NKRO_ENABLE = no
OLED_ENABLE = yes
RGBLIGHT_ENABLE = yes
SPACE_CADET_ENABLE = no
