description: Momentary layer chord with independently released layers

compatible: "zmk,behavior-layer-chord"

include: one_param.yaml

properties:
  parent-layer:
    type: int
    required: true
  child-layer:
    type: int
    required: true
  parent-overlay-layer:
    type: int
  child-overlay-layer:
    type: int
  parent-position:
    type: int
    required: true
  child-position:
    type: int
    required: true
