description: Momentary layer and modifier chord with independent releases

compatible: "zmk,behavior-layer-mod-chord"

include: zero_param.yaml

properties:
  bindings:
    type: phandle-array
    required: true
  sticky-bindings:
    type: phandle-array
    specifier-space: binding
    required: true
  tapping-term-ms:
    type: int
    required: true
  layer:
    type: int
    required: true
  layer-position:
    type: int
    required: true
  modifier-positions:
    type: array
    required: true
  activation-layers:
    type: array
    required: true
  trigger-modifiers:
    type: int
    required: true
  combo-term-ms:
    type: int
    required: true
