manifest:
  remotes:
    - name: moergo-sc
      url-base: https://github.com/moergo-sc
    - name: urob
      url-base: https://github.com/urob
    - name: rzssh
      url-base: https://github.com/rzssh

  projects:
    - name: zmk
      remote: moergo-sc
      revision: 2f73a230e2fc7b2bd64a9736181e87bf54338131
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: bc114546392b4615ac90a99140eaf21dde31209d
    - name: zmk-adaptive-key
      remote: rzssh
      revision: 8a835ea157c23de50e0808945a4a0a47895fd2c7
    - name: zmk-vim-mode
      remote: rzssh
      revision: 34a8dd2187c6335f5890c1b5c43fabdfac75ac86

  self:
    path: config
