manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: rzssh
      url-base: https://github.com/rzssh

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 268b1b1e82150460f00fd701bcd08583d5c75d29
      import:
        file: app/west.yml
        path-prefix: ""
    - name: zmk-helpers
      remote: urob
      revision: bc114546392b4615ac90a99140eaf21dde31209d
      path: modules/zmk/helpers
    - name: zmk-adaptive-key
      remote: rzssh
      revision: 95083d7bb0c4b76dbc475c15bf352775932d87ef
      path: modules/zmk/adaptive-key
    - name: zmk-vim-mode
      remote: rzssh
      revision: 34a8dd2187c6335f5890c1b5c43fabdfac75ac86
      path: modules/zmk/vim-mode

  self:
    path: config
