board: xiao_ble/nrf52840/zmk
default_builds: [adept]
builds:
  adept:
    shield: adept
    snippets: studio-rpc-usb-uart
  reset:
    shield: adept
    label: settings_reset
    snippets: studio-rpc-usb-uart
