manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: rzssh
      url-base: https://github.com/rzssh

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 268b1b1e82150460f00fd701bcd08583d5c75d29
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: bc114546392b4615ac90a99140eaf21dde31209d
    - name: zmk-auto-layer
      remote: urob
      revision: b50d514219c5ad61198f9a8be137c59d0674b11c
    - name: zmk-adaptive-key
      remote: rzssh
      revision: 540b774f6da9d763e61bc64b694790757ed3bd84
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: e6b467792a1dabef8cfa5c9fd26bfefc9c16662b

  self:
    path: config
