[layers.Graphium.core30]
rows = [
  ["B", "L", "D", "W", "G", "Y", "F", "O", "U", "J"],
  [{ tap = "N", hold = "LGUI", hand = "left" }, { tap = "R", hold = "LALT", hand = "left" }, { tap = "T", hold = "LCTRL", hand = "left" }, { tap = "S", hold = "LSHFT", hand = "left", adaptive = "graphium" }, "V", "K", { tap = "H", hold = "RSHFT", hand = "right" }, { tap = "A", hold = "RCTRL", hand = "right" }, { tap = "E", hold = "RALT", hand = "right" }, { tap = "I", hold = "RGUI", hand = "right" }],
  ["X", "M", "C", "P", { use = "dot_qmark" }, { use = "comma_excl" }],
  [{ layer = "Nav", mode = "momentary" }, "SPACE", { use = "thumb_magic" }, { layer = "Sym", mode = "momentary" }],
]

[layers.Graphium.core34]
rows = [
  ["B", "L", "D", "W", "Z", "J", "F", "O", "U", { use = "dot_qmark" }],
  [{ tap = "N", hold = "LGUI", hand = "left" }, { tap = "R", hold = "LALT", hand = "left" }, { tap = "T", hold = "LCTRL", hand = "left" }, { tap = "S", hold = "LSHFT", hand = "left", adaptive = "graphium" }, "G", "Y", { tap = "H", hold = "RSHFT", hand = "right" }, { tap = "A", hold = "RCTRL", hand = "right" }, { tap = "E", hold = "RALT", hand = "right" }, { tap = "I", hold = "RGUI", hand = "right" }],
  ["Q", "X", "M", "C", "V", "K", "P", { use = "sqt_dqt" }, { use = "minus_slash" }, { use = "comma_excl" }],
  [{ layer = "Sym", mode = "momentary" }, { use = "bspc_plain_nav" }, "SPACE", { layer = "Num", mode = "momentary" }],
]

[layers.Vestnik.core30]
rows = [
  ["Ш", "Г", "Р", "Б", "М", "Ь", "П", "О", "У", "Ю"],
  [{ tap = "С", hold = "LGUI", hand = "left" }, { tap = "Т", hold = "LALT", hand = "left" }, { tap = "Н", hold = "LCTRL", hand = "left", adaptive = "vestnik" }, { tap = "К", hold = "LSHFT", hand = "left" }, "Ч", "Ж", { tap = "В", hold = "RSHFT", hand = "right" }, { tap = "А", hold = "RCTRL", hand = "right" }, { tap = "Е", hold = "RALT", hand = "right" }, { tap = "И", hold = "RGUI", hand = "right" }],
  ["З", "Л", "Д", "Й", "Ы", "Я"],
  [{ layer = "Nav", mode = "momentary" }, "SPACE", { use = "thumb_magic" }, { layer = "Sym", mode = "momentary" }],
]

[layers.Vestnik.core34]
rows = [
  ["Ш", "З", "Р", "М", "Х", "Ф", "П", { tap = "О", adaptive = "vestnik_core34" }, "У", "Ю"],
  [{ tap = "С", hold = "LGUI", hand = "left" }, { tap = "Т", hold = "LALT", hand = "left" }, { tap = "Н", hold = "LCTRL", hand = "left" }, { tap = "К", hold = "LSHFT", hand = "left" }, "Б", "Г", { tap = "В", hold = "RSHFT", hand = "right" }, { tap = "А", hold = "RCTRL", hand = "right" }, { tap = "Е", hold = "RALT", hand = "right" }, { tap = "И", hold = "RGUI", hand = "right" }],
  ["Щ", "Ц", "Л", "Д", "Ч", "Ж", { use = "vestnik_short_sign" }, "Ы", "Я", "Э"],
  [{ layer = "Sym", mode = "momentary" }, { use = "bspc_plain_nav" }, "SPACE", { layer = "Num", mode = "momentary" }],
]

[layers.Nav.core30]
rows = [
  ["none", { key = "O", mods = ["LGUI"] }, { key = "U", mods = ["LGUI"] }, { use = "tab_previous" }, { use = "tab_next" }, { mouse = "SCRL_UP" }, { os = "home" }, "UP", { os = "end" }, "PG_UP"],
  [{ use = "osm_gui" }, { use = "osm_alt" }, { use = "osm_ctrl" }, { use = "osm_shift" }, "none", { mouse = "SCRL_DOWN" }, "LEFT", "DOWN", "RIGHT", "PG_DN"],
  ["none", { use = "select_line" }, { use = "select_word" }, "none", "none", "none"],
  ["none", { layer = "Mouse", mode = "momentary" }, "none", "trans"],
]

[layers.Nav.core34]
rows = [
  [{ feature = "nav_meta_keys", enabled = "ESC" }, { key = "O", mods = ["LGUI"] }, { key = "U", mods = ["LGUI"] }, { use = "tab_previous" }, { use = "tab_next" }, { mouse = "SCRL_UP" }, { os = "home" }, "UP", { os = "end" }, "PG_UP"],
  [{ use = "osm_gui" }, { use = "osm_alt" }, { use = "osm_ctrl" }, { use = "osm_shift" }, { feature = "nav_meta_keys", enabled = { os = "delete_word_left" } }, { mouse = "SCRL_DOWN" }, "LEFT", "DOWN", "RIGHT", "PG_DN"],
  [{ feature = "nav_editing_keys", enabled = { use = "undo_redo" } }, { feature = "nav_editing_keys", enabled = { os = "cut" } }, { feature = "nav_editing_keys", enabled = { os = "copy" } }, { feature = "nav_editing_keys", enabled = { os = "paste" } }, { feature = "nav_editing_keys", enabled = { os = "select_all" } }, { use = "caps_word_lock", draw = "CAPS" }, { feature = "nav_meta_keys", enabled = "RET" }, { feature = "nav_meta_keys", enabled = "TAB" }, { feature = "nav_meta_keys", enabled = "BSPC" }, { feature = "nav_meta_keys", enabled = "DEL" }],
  [{ layer = "Sym", mode = "momentary" }, "trans", { feature = "nav_meta_keys", enabled = "RET" }, { layer = "Num", mode = "momentary" }],
]

[layers.Sym.core30]
rows = [
  ["GRAVE", { use = "bslh_qmark" }, { use = "slash_excl" }, "DLLR", "DQT", "PRCNT", { use = "brace" }, { use = "paren" }, { use = "square" }, { use = "angle" }],
  ["CARET", "UNDER", "COLON", "EQUAL", "MINUS", "AT", { use = "osm_shift" }, { use = "osm_ctrl" }, { use = "osm_alt" }, { use = "osm_gui" }],
  ["PIPE", "AMPS", "PLUS", "HASH", "STAR", "SEMI"],
  ["trans", "SPACE", { layer = "Fn", mode = "momentary" }, "none"],
]

[layers.Sym.core34]
rows = [
  ["PRCNT", "HASH", "STAR", "AMPS", "PIPE", { use = "grave_tilde" }, { use = "lpar_lbkt" }, { use = "rpar_rbkt" }, { use = "lbrc_lt" }, { use = "rbrc_gt" }],
  [{ use = "osm_gui" }, { use = "osm_alt" }, { use = "osm_ctrl" }, { use = "osm_shift" }, "AT", "PLUS", { use = "equal_plain" }, "COLON", "UNDER", { use = "semi_plain" }],
  ["EXCL", "CARET", "DLLR", "DQT", "SQT", { use = "bslh_plain" }, { use = "minus_plain" }, { use = "slash_plain" }, { use = "dot_plain" }, "QMARK"],
  ["trans", { layer = "Nav", mode = "momentary" }, "SPACE", { layer = "Num", mode = "momentary" }],
]

[layers.Num.core30]
rows = [
  [{ key = "G", mods = ["LSHFT"] }, "N7", "N8", "N9", "UP", "PRCNT", "STAR", "FSLH", "EQUAL", "DOT"],
  ["N0", "N1", "N2", "N3", "DOWN", "COLON", { use = "osm_shift" }, { use = "osm_ctrl" }, { use = "osm_alt" }, { use = "osm_gui" }],
  ["N4", "N5", "N6", "PLUS", "MINUS", "COMMA"],
  ["none", "none", "none", "none"],
]

[layers.Num.core34]
rows = [
  ["FSLH", "N7", "N8", "N9", "STAR", "DOT", "LPAR", "RPAR", "LBKT", "RBKT"],
  ["N0", "N1", "N2", "N3", "PLUS", "EQUAL", { use = "osm_shift" }, { use = "osm_ctrl" }, { use = "osm_alt" }, { use = "osm_gui" }],
  ["COLON", "N4", "N5", "N6", "SEMI", "COMMA", "LBRC", "RBRC", "LT", "GT"],
  [{ layer = "Sym", mode = "momentary" }, "trans", { layer = "Fn", mode = "momentary" }, "trans"],
]

[layers.Fn.core30]
rows = [
  [{ use = "bootloader" }, "F7", "F8", "F9", "F12", { use = "output_toggle" }, { use = "lang_en" }, { use = "lang_ru" }, { use = "lang_ua" }, { use = "bootloader" }],
  ["F10", "F1", "F2", "F3", "F11", { use = "bt_clear" }, "LSHFT", "LCTRL", "LALT", "LGUI"],
  ["F4", "F5", "F6", { use = "bt_0" }, { use = "bt_1" }, { use = "bt_2" }],
  ["none", "none", "none", "none"],
]

[layers.Fn.core34]
rows = [
  [{ use = "bootloader" }, "F7", "F8", "F9", "F12", { use = "output_toggle" }, { use = "lang_en" }, { use = "lang_ru" }, { use = "lang_ua" }, { use = "bootloader" }],
  ["PSCRN", "F1", "F2", "F3", "F11", "none", "LSHFT", "LCTRL", "LALT", "LGUI"],
  ["PAUSE_BREAK", "F4", "F5", "F6", "F10", { use = "bt_clear" }, { use = "bt_0" }, { use = "bt_1" }, { use = "bt_2" }, { use = "bt_3" }],
  ["none", "none", "none", "none"],
]

[layers.Mouse.core30]
rows = [
  ["none", "none", "none", "none", "none", { mouse = "SCRL_UP" }, { mouse = "SCRL_LEFT" }, { mouse = "MOVE_UP" }, { mouse = "SCRL_RIGHT" }, "PG_UP"],
  ["LGUI", "LALT", "LCTRL", "LSHFT", "none", { mouse = "SCRL_DOWN" }, { mouse = "MOVE_LEFT" }, { mouse = "MOVE_DOWN" }, { mouse = "MOVE_RIGHT" }, "PG_DN"],
  ["none", "none", "none", { mouse = "MCLK" }, { mouse = "MB4" }, { mouse = "MB5" }],
  ["none", "none", { mouse = "LCLK" }, { mouse = "RCLK" }],
]

[layers.Mouse.core34]
rows = [
  ["none", "none", "none", "none", "none", { mouse = "SCRL_UP" }, { mouse = "SCRL_LEFT" }, { mouse = "MOVE_UP" }, { mouse = "SCRL_RIGHT" }, "PG_UP"],
  ["LGUI", "LALT", "LCTRL", "LSHFT", "none", { mouse = "SCRL_DOWN" }, { mouse = "MOVE_LEFT" }, { mouse = "MOVE_DOWN" }, { mouse = "MOVE_RIGHT" }, "PG_DN"],
  [{ use = "undo_redo" }, { os = "cut" }, { os = "copy" }, { os = "paste" }, { os = "select_all" }, "none", { mouse = "MCLK" }, "none", { mouse = "MB4" }, { mouse = "MB5" }],
  ["none", "none", { mouse = "LCLK" }, { mouse = "RCLK" }],
]

[setups.right_space_split]
thumb_tap_feature = "layer_thumb_taps"

[setups.right_space_split.thumbs]
alpha = [{ layer = "Sym", mode = "momentary" }, { use = "bspc_plain_nav" }, "SPACE", { layer = "Num", mode = "momentary" }]
Nav = [{ layer = "Sym", mode = "momentary" }, "trans", "SPACE", { layer = "Num", mode = "momentary" }]
Sym = ["trans", { layer = "Nav", mode = "momentary" }, "SPACE", { layer = "Num", mode = "momentary" }]
Num = [{ layer = "Sym", mode = "momentary" }, "trans", { layer = "Fn", mode = "momentary" }, "trans"]

[setups.right_space_split.thumb_taps]
alpha = [{ use = "esc_sym" }, { use = "bspc_plain_nav" }, "SPACE", { use = "enter_num" }]
Nav = [{ use = "esc_sym" }, "trans", "SPACE", { use = "enter_num" }]
Sym = ["trans", { layer = "Nav", mode = "momentary" }, "SPACE", { use = "enter_num" }]
Num = [{ use = "esc_sym" }, "trans", { layer = "Fn", mode = "momentary" }, "trans"]

[setups.left_space_split.thumbs]
alpha = [{ layer = "Nav", mode = "momentary" }, "SPACE", { use = "thumb_magic" }, { layer = "Sym", mode = "momentary" }]
Nav = ["trans", { layer = "Mouse", mode = "momentary" }, "none", "trans"]
Sym = ["trans", "SPACE", { layer = "Fn", mode = "momentary" }, "trans"]
Num = ["trans", "none", { layer = "Fn", mode = "momentary" }, "trans"]

[setups.left_space_split.layers.Sym]
rows = [
  [{ use = "grave_tilde" }, { use = "star_caret" }, { use = "hash_dollar" }, { use = "amp_percent" }, "PIPE", { use = "dot_plain" }, "LPAR", "RPAR", "LBKT", "RBKT"],
  [{ use = "semi_plain" }, "UNDER", "COLON", { use = "equal_plain" }, "PLUS", "AT", { use = "osm_shift" }, { use = "osm_ctrl" }, { use = "osm_alt" }, { use = "osm_gui" }],
  ["QMARK", "EXCL", { use = "slash_plain" }, { use = "minus_plain" }, { use = "bslh_plain" }, "COMMA", "LBRC", "RBRC", "LT", "GT"],
  ["trans", "SPACE", { layer = "Fn", mode = "momentary" }, "trans"],
]

[setups.left_space_combined]
disabled_layers = ["Num"]
draw_aliases = { Sym = "SymNum" }

[setups.left_space_combined.thumbs]
alpha = [{ layer = "Nav", mode = "momentary" }, "SPACE", { use = "thumb_magic" }, { layer = "Sym", mode = "momentary" }]
Nav = ["trans", { layer = "Mouse", mode = "momentary" }, { feature = "nav_meta_keys", enabled = "RET" }, "none"]
Sym = ["N0", "SPACE", { layer = "Fn", mode = "momentary" }, "trans"]
Num = ["none", "SPACE", { layer = "Fn", mode = "momentary" }, "trans"]

[setups.left_space_combined.layers.Sym]
rows = [
  ["AT", "N9", "N8", "N7", "HASH", "EXCL", "COLON", { use = "equal_plain" }, "PLUS", "QMARK"],
  [{ use = "slash_plain" }, "N3", "N2", "N1", "AMPS", "DQT", { use = "osm_shift" }, { use = "osm_ctrl" }, { use = "osm_alt" }, { use = "osm_gui" }],
  [{ use = "bslh_plain" }, "N6", "N5", "N4", "PIPE", { use = "grave_tilde" }, { use = "minus_plain" }, "UNDER", "STAR", { use = "semi_plain" }],
  ["N0", "SPACE", { layer = "Fn", mode = "momentary" }, "trans"],
]

[setups.left_space_combined.layers.Num]
rows = [
  ["none", "N7", "N8", "N9", "none", "none", "none", "none", "none", "none"],
  ["N0", "N1", "N2", "N3", "none", "none", { use = "osm_shift" }, { use = "osm_ctrl" }, { use = "osm_alt" }, { use = "osm_gui" }],
  ["none", "N4", "N5", "N6", "none", "none", "none", "none", "none", "none"],
  ["none", "SPACE", { layer = "Fn", mode = "momentary" }, "trans"],
]

[layers.Magic.glove80_80]
bindings = [
  "none", "none", "none", "none", "none", "none", "none", "none", "none", "none",
  "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none",
  { use = "bt_clear_all" }, "none", { rgb = "hue_decrease" }, { rgb = "hue_increase" }, "none", "none", "none", "none", "none", "none", "none", { use = "bt_clear" },
  { use = "bootloader" }, { rgb = "effect_reverse" }, { rgb = "brightness_decrease" }, { rgb = "brightness_increase" }, { rgb = "effect_forward" }, { rgb = "toggle" }, "none", { use = "bt_0" }, { use = "bt_1" }, { use = "bt_2" }, { use = "bt_3" }, { use = "bootloader" },
  { use = "reset" }, { rgb = "speed_decrease" }, { rgb = "saturation_decrease" }, { rgb = "saturation_increase" }, { rgb = "speed_increase" }, "none", "none", "none", "none", "none", "none", "none", "none", { rgb = "hue_increase" }, { rgb = "hue_decrease" }, "none", { use = "output_toggle" }, { use = "reset" },
  "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none",
]
