[layers.Graphium.core30]
rows = [
  ["B", "L", "D", "W", "G", "Y", "F", "O", "U", "J"],
  [{ tap = "N", hold = "LGUI", hand = "left" }, { tap = "R", hold = "LALT", hand = "left" }, { tap = "T", hold = "LCTRL", hand = "left" }, { tap = "S", hold = "LSHFT", hand = "left", adaptive = "graphium" }, "V", "K", { tap = "H", hold = "RSHFT", hand = "right" }, { tap = "A", hold = "RCTRL", hand = "right" }, { tap = "E", hold = "RALT", hand = "right" }, { tap = "I", hold = "RGUI", hand = "right" }],
  ["X", "M", "C", "P", { use = "dot_qmark" }, { use = "comma_excl" }],
  [{ layer = "Nav", mode = "momentary" }, "SPACE", { use = "thumb_magic" }, { layer = "Sym", mode = "momentary" }],
]

[layers.Graphium.core34]
rows = [
  ["B", "L", "D", "W", "Z", "SQT", "F", "O", "U", "J"],
  [{ tap = "N", hold = "LGUI", hand = "left" }, { tap = "R", hold = "LALT", hand = "left" }, { tap = "T", hold = "LCTRL", hand = "left" }, { tap = "S", hold = "LSHFT", hand = "left", adaptive = "graphium" }, "G", "Y", { tap = "H", hold = "RSHFT", hand = "right" }, { tap = "A", hold = "RCTRL", hand = "right" }, { tap = "E", hold = "RALT", hand = "right" }, { tap = "I", hold = "RGUI", hand = "right" }],
  ["Q", "X", "M", "C", "V", "K", "P", { use = "dot_colon" }, { use = "comma_semi" }, { use = "qmark_excl" }],
  [{ layer = "Nav", mode = "momentary" }, "SPACE", { use = "osm_shift", draw = "LSHFT" }, { layer = "Sym", mode = "sticky" }],
]

[layers.Vestnik.core30]
rows = [
  ["Ш", "Г", "Р", "Б", "М", "Ь", "П", "О", "У", "Ю"],
  [{ tap = "С", hold = "LGUI", hand = "left" }, { tap = "Т", hold = "LALT", hand = "left" }, { tap = "Н", hold = "LCTRL", hand = "left", adaptive = "vestnik" }, { tap = "К", hold = "LSHFT", hand = "left" }, "Ч", "Ж", { tap = "В", hold = "RSHFT", hand = "right" }, { tap = "А", hold = "RCTRL", hand = "right" }, { tap = "Е", hold = "RALT", hand = "right" }, { tap = "И", hold = "RGUI", hand = "right" }],
  ["З", "Л", "Д", "Й", "Ы", "Я"],
  [{ layer = "Nav", mode = "momentary" }, "SPACE", { use = "thumb_magic" }, { layer = "Sym", mode = "momentary" }],
]

[layers.Vestnik.core34]
rows = [
  ["Ш", "З", "Р", "М", "Х", "Ф", "П", "О", "У", "Ю"],
  [{ tap = "С", hold = "LGUI", hand = "left" }, { tap = "Т", hold = "LALT", hand = "left" }, { tap = "Н", hold = "LCTRL", hand = "left", adaptive = "vestnik_core34" }, { tap = "К", hold = "LSHFT", hand = "left" }, "Б", "Г", { tap = "В", hold = "RSHFT", hand = "right" }, { tap = "А", hold = "RCTRL", hand = "right" }, { tap = "Е", hold = "RALT", hand = "right" }, { tap = "И", hold = "RGUI", hand = "right" }],
  ["Щ", "Ц", "Л", "Д", "Ч", "Ж", { use = "vestnik_short_sign" }, "Ы", "Я", "Э"],
  [{ layer = "Nav", mode = "momentary" }, "SPACE", { use = "osm_shift", draw = "LSHFT" }, { layer = "Sym", mode = "sticky" }],
]

[layers.Vim.core30]
rows = [
  ["trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans"],
  ["trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans"],
  ["trans", "trans", "trans", "trans", "trans", "trans"],
  ["trans", "trans", "trans", "trans"],
]

[layers.Vim.core34]
rows = [
  ["trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans"],
  ["trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans"],
  ["trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans", "trans"],
  ["trans", "trans", "trans", "trans"],
]

[layers.Nav.core30]
rows = [
  ["none", { key = "O", mods = ["LGUI"] }, { key = "U", mods = ["LGUI"] }, { use = "tab_previous" }, { use = "tab_next" }, { mouse = "SCRL_UP" }, { os = "home" }, "UP", { os = "end" }, "PG_UP"],
  [{ use = "osm_gui" }, { use = "osm_alt" }, { use = "osm_ctrl" }, { use = "osm_shift" }, "none", { mouse = "SCRL_DOWN" }, "LEFT", "DOWN", "RIGHT", "PG_DN"],
  ["none", { use = "select_line" }, { use = "select_word" }, "none", "none", "none"],
  ["none", { layer = "Mouse", mode = "momentary" }, "none", "trans"],
]

[layers.Nav.core34]
rows = [
  [{ use = "nav_overview_opacity" }, { key = "PG_UP", mods = ["LGUI"], draw = "nav_workspace_up" }, { key = "PG_DN", mods = ["LGUI"], draw = "nav_workspace_down" }, { use = "tab_previous", draw = "nav_tab_previous" }, { use = "tab_next", draw = "nav_tab_next" }, { use = "nav_page_up" }, { key = "P", mods = ["LGUI"], draw = "nav_files" }, "UP", { key = "F", mods = ["LGUI"], draw = "nav_window" }, { key = "F1", mods = ["LGUI"], draw = "nav_region" }],
  [{ use = "osm_gui" }, { use = "osm_alt" }, { use = "osm_ctrl" }, { use = "osm_shift" }, { key = "R", mods = ["LGUI"], draw = "nav_launcher" }, { use = "nav_page_down" }, "LEFT", "DOWN", "RIGHT", { key = "F2", mods = ["LGUI"], draw = "nav_display" }],
  [{ use = "undo_redo" }, { os = "cut" }, { os = "copy" }, { os = "paste" }, { os = "select_all" }, { key = "F3", mods = ["LGUI"], draw = "nav_tools" }, { key = "F7", mods = ["LGUI"], draw = "nav_media_previous" }, { key = "F8", mods = ["LGUI"], draw = "nav_media_play" }, { key = "F9", mods = ["LGUI"], draw = "nav_media_next" }, { key = "F4", mods = ["LGUI"], draw = "nav_speech" }],
  ["trans", { layer = "Mouse", mode = "momentary" }, { use = "nav_pointer" }, { layer = "Sym", mode = "sticky" }],
]

[layers.Sym.core30]
rows = [
  ["GRAVE", { use = "bslh_qmark" }, { use = "slash_excl" }, "DLLR", "DQT", "PRCNT", { use = "brace" }, { use = "paren" }, { use = "square" }, { use = "angle" }],
  ["CARET", "UNDER", "COLON", "EQUAL", "MINUS", "AT", { use = "osm_shift" }, { use = "osm_ctrl" }, { use = "osm_alt" }, { use = "osm_gui" }],
  ["PIPE", "AMPS", "PLUS", "HASH", "STAR", "SEMI"],
  ["trans", "SPACE", { layer = "Fn", mode = "momentary" }, "none"],
]

[layers.Sym.core34]
rows = [
  ["CARET", "LBKT", "LBRC", "LPAR", "LT", "GT", "RPAR", "RBRC", "RBKT", "TILDE"],
  ["MINUS", "STAR", "UNDER", "EQUAL", "AT", "HASH", { use = "osm_shift" }, { use = "osm_ctrl" }, { use = "osm_alt" }, { use = "osm_gui" }],
  ["PLUS", "COLON", "SEMI", "FSLH", "PRCNT", "DLLR", "BSLH", "AMPS", "PIPE", "GRAVE"],
  [{ layer = "Nav", mode = "momentary" }, "SPACE", { layer = "Fn", mode = "momentary" }, "trans"],
]

[layers.Num.core30]
rows = [
  [{ key = "G", mods = ["LSHFT"] }, "N7", "N8", "N9", "UP", "PRCNT", "STAR", "FSLH", "EQUAL", "DOT"],
  ["N0", "N1", "N2", "N3", "DOWN", "COLON", { use = "osm_shift" }, { use = "osm_ctrl" }, { use = "osm_alt" }, { use = "osm_gui" }],
  ["N4", "N5", "N6", "PLUS", "MINUS", "COMMA"],
  ["none", "none", "none", "none"],
]

[layers.Num.core34]
rows = [
  ["none", "EQUAL", "FSLH", "STAR", "none", "none", "N7", "N8", "N9", "none"],
  [{ use = "osm_gui" }, { use = "osm_alt" }, { use = "osm_ctrl" }, { use = "osm_shift" }, "UNDER", "none", "N1", "N2", "N3", "N0"],
  ["COMMA", "DOT", "MINUS", "PLUS", "none", "none", "N4", "N5", "N6", "none"],
  ["trans", "trans", "trans", "trans"],
]

[layers.Fn.core30]
rows = [
  [{ use = "bootloader" }, "F7", "F8", "F9", "F12", { use = "output_toggle" }, { use = "lang_en" }, { use = "lang_ru" }, { use = "lang_ua" }, { use = "bootloader" }],
  ["F10", "F4", "F5", "F6", "F11", { use = "bt_clear" }, "LSHFT", "LCTRL", "LALT", "LGUI"],
  ["F1", "F2", "F3", { use = "bt_0" }, { use = "bt_1" }, { use = "bt_2" }],
  ["none", "none", "none", "none"],
]

[layers.Fn.core34]
rows = [
  [{ use = "bootloader" }, "F7", "F8", "F9", "F12", { use = "output_toggle" }, { use = "lang_en" }, { use = "lang_ru" }, { use = "lang_ua" }, { use = "bootloader" }],
  ["PSCRN", "F4", "F5", "F6", "F11", "none", "LSHFT", "LCTRL", "LALT", "LGUI"],
  ["PAUSE_BREAK", "F1", "F2", "F3", "F10", { use = "bt_clear" }, { use = "bt_0" }, { use = "bt_1" }, { use = "bt_2" }, { use = "bt_3" }],
  ["none", "none", "none", "none"],
]

[layers.Mouse.core30]
rows = [
  ["none", "none", "none", "none", "none", { mouse = "SCRL_UP" }, { mouse = "SCRL_LEFT" }, { mouse = "MOVE_UP" }, { mouse = "SCRL_RIGHT" }, "PG_UP"],
  ["LGUI", "LALT", "LCTRL", "LSHFT", "none", { mouse = "SCRL_DOWN" }, { mouse = "MOVE_LEFT" }, { mouse = "MOVE_DOWN" }, { mouse = "MOVE_RIGHT" }, "PG_DN"],
  ["none", "none", "none", { mouse = "MCLK" }, { mouse = "MB4" }, { mouse = "MB5" }],
  ["none", "none", { mouse = "LCLK" }, { mouse = "RCLK" }],
]

[layers.Mouse.core34]
rows = [
  ["none", "pointer_bisect", "pointer_hover", "pointer_click", "none", { mouse = "SCRL_UP" }, { mouse = "SCRL_LEFT" }, { mouse = "MOVE_UP" }, { mouse = "SCRL_RIGHT" }, "PG_UP"],
  ["LGUI", "LALT", "LCTRL", "LSHFT", "none", { mouse = "SCRL_DOWN" }, { mouse = "MOVE_LEFT" }, { mouse = "MOVE_DOWN" }, { mouse = "MOVE_RIGHT" }, "PG_DN"],
  [{ use = "undo_redo" }, { os = "cut" }, { os = "copy" }, { os = "paste" }, { os = "select_all" }, "none", { mouse = "MCLK" }, "none", { mouse = "MB4" }, { mouse = "MB5" }],
  ["none", "none", { mouse = "LCLK" }, { mouse = "RCLK" }],
]

[layers.Magic.glove80_80]
bindings = [
  "none", "none", "none", "none", "none", "none", "none", "none", "none", "none",
  "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none",
  { use = "bt_clear_all" }, "none", { rgb = "hue_decrease" }, { rgb = "hue_increase" }, "none", "none", "none", "none", "none", "none", "none", { use = "bt_clear" },
  { use = "bootloader" }, { rgb = "effect_reverse" }, { rgb = "brightness_decrease" }, { rgb = "brightness_increase" }, { rgb = "effect_forward" }, { rgb = "toggle" }, "none", { use = "bt_0" }, { use = "bt_1" }, { use = "bt_2" }, { use = "bt_3" }, { use = "bootloader" },
  { use = "reset" }, { rgb = "speed_decrease" }, { rgb = "saturation_decrease" }, { rgb = "saturation_increase" }, { rgb = "speed_increase" }, "none", "none", "none", "none", "none", "none", "none", "none", { rgb = "hue_increase" }, { rgb = "hue_decrease" }, "none", { use = "output_toggle" }, { use = "reset" },
  "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none", "none",
]
