USER_NAME := razen

BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
GRAVE_ESC_ENABLE = no
HAPTIC_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
NKRO_ENABLE = no
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
RGB_MATRIX_ENABLE = yes
SPACE_CADET_ENABLE = no
